name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (frontend)
        run: |
          docker build -t myapp ./frontend

      - name: Run Docker container in background
        run: |
          docker run -d -p 3000:3000 --name my-running-app myapp
          sleep 10  # give it a few seconds to boot

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
            target: 'http://localhost:3000'
            fail_action: false
            docker_name: ghcr.io/zaproxy/zaproxy:stable
            allow_issue_writing: false
            artifact_name: zapscan

