name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (frontend)
        run: |
          docker build -t myapp ./frontend

      - name: Run Docker container in background
        run: |
          docker run -d -p 3000:3000 --name my-running-app myapp
          sleep 10  # give it a few seconds to boot

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zapscan_${{ github.run_id }}
          path: |
            report_html.html
            report_json.json
