name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast-zap:
    runs-on: ubuntu-latest

    services:
      web:
        name: myapp
        build:
          context: ./frontend
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl -f http://localhost:3000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
